### ISSUE TITLE
Trouver les images des acteurs de la simulation

### ISSUE THREAD

**Issue by Toumani** [Toumani/elevator-sim#1]

**Comment by Youssef-kabili** [comment]
Oui , j'ai l'honneur de traiter cette ticket

**Comment by Toumani** [comment]
Je vais me charger de cette tâche puisque @Youssef-kabili ne semble pas très impliqué ..

**Comment by Toumani** [comment]
Retrouver les images pour la simulation dans le dossier https://github.com/Toumani/elevator-sim/blob/main/src/main/resources/.
Je ferme le ticket.
